# Generated by Django 3.2.7 on 2021-09-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Event', help_text='Insert your countdown Title!', max_length=64, null=True)),
                ('date', models.DateField(help_text='Select the date!')),
            ],
        ),
    ]
